version: '3'

services:
  redis:
    image: 'redis:latest'
    container_name: redis-container
    ports:
      - '6379:6379'
    volumes:
      - './redis/redis.conf:/etc/redis/redis.conf'
    command: ['redis-server', '/etc/redis/redis.conf']
    networks:
      - my-network

  node-app:
    build:
      context: ./application
      dockerfile: Dockerfile
    container_name: node-app-container
    volumes:
      - './application:/app'
    ports:
      - '8000:8000'
    depends_on:
      - redis
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
